export const Categories = [
	{
		category_name: "Stress, Anxiety &  Worry",
		ids: [
			"social-media-anxiety-disorder",
			"health-anxiety-hypochondriasis",
			"agoraphobia-social-phobia",
			"performance-anxiety-evaluation-fear",
			"ai-anxiety-technophobia-fear-ai",
			"generalized-anxiety-disorder",
		],
	},
	{
		category_name: "Fears & Phobias",
		ids: [
			"cynophobia-fear-dogs",
			"astraphobia-fear-storms",
			"arachnophobia-fear-spiders",
			"ophidiophobia-fear-snakes",
			"claustrophobia-fear-enclosed-spaces",
			"trypanophobia-fear-needles",
			"acrophobia-fear-heights",
			"thanatophobia-death-anxiety",
			"aerophobia-fear-flying",
			"chronophobia-fear-time-future",
			"moral-injury-values-violation",
			"other-fears-phobias",
		],
	},
	{
		category_name: "Mood Disorders",
		ids: [
			"depressed-suicidal-major-depressive-disorder",
			"burnout-exhaustion-depersonalization",
			"bpd-bipolar-disorder",
			"seasonal-affective-disorder-sad",
			"perinatal-depression-paternal-postpartum-depression",
			"menopausal-depression",
			"other-mood-disorders",
		],
	},
	{
		category_name: "Neurodevelopmental",
		ids: [
			"adhd-attention-deficit-hyperactivity-disorder",
			"asd-autism-aspergers-autistic-spectrum-disorder",
			"dcd-dyspraxia-developmental-coordination-disorder",
			"spd-sensory-processing-disorder",
			"dyslexia-reading-disorder",
			"dyscalculia",
			"misophonia",
			"other-neurodevelopmental-issues",
		],
	},
	{
		category_name: "Addictions",
		ids: [
			"screen-addiction",
			"alcohol-substance-abuse",
			"porn-addiction-sexual-compulsivity",
			"gambling-addiction",
			"food-addiction",
			"sex-addiction",
			"other-addictions",
		],
	},
	{
		category_name: "Neurological & Physical",
		ids: [
			"migraines",
			"chronic-pain-psychosomatic",
			"epilepsy-seizure-disorders",
			"tics-tourette-syndrome-tic-disorders",
			"insomnia-sleep-hyperarousal",
			"anxiety-related-gastrointestinal-issues",
			"anxiety-health-conditions",
			"other-neurological-issues",
		],
	},
	{
		category_name: "Performance & Self-Perception",
		ids: [
			"test-anxiety",
			"perfectionism",
			"body-dysmorphia",
			"self-esteem-identity-issues",
			"imposter-syndrome",
			"other-performance-issues",
		],
	},
	{
		category_name: "Obsessive-Compulsive Spectrum",
		ids: [
			"ocd-obsessive-compulsive-disorder",
			"eating-disorders-anorexia-bulimia-binge",
			"trichotillomania-hair-pulling",
			"hoarding-disorder",
			"cutting-self-harm",
			"other-ocd-spectrum",
		],
	},
	{
		category_name: "Attachment & Relational",
		ids: [
			"divorce-relational-trauma-family-systems-stress",
			"anxious-avoidant-attachment-relational-patterns",
			"loneliness-social-disconnection",
			"rejection-sensitivity",
			"fear-of-intimacy-commitment-fear",
			"sexual-dysfunction-performance-anxiety-impotence",
			"relationship-jealousy-insecurity",
			"codependency-relational-enmeshment",
			"other-attachment-issues",
		],
	},
	{
		category_name: "Communication Disorders",
		ids: [
			"glossophobia-fear-public-speaking",
			"stuttering-childhood-onset-fluency-disorder",
			"selective-mutism",
			"dysgraphia",
			"aphasia-language-disorder",
			"other-communication-issues",
		],
	},
	{
		category_name: "Trauma & Crisis",
		ids: [
			"ptsd-post-traumatic-stress-disorder",
			"rape-sexual-assault",
			"stockholm-syndrome-trauma-bonding",
			"developmental-trauma-childhood-trauma",
			"cult-recovery-religious-trauma-damnation-fear",
			"trauma-drama-etc",
		],
	},
	{
		category_name: "Power & Control",
		ids: [
			"ied-rage-intermittent-explosive-disorder",
			"gun-addiction-weapons-obsession",
			"homicidal-ideation-violent-urges",
			"paranoia-scelerephobia-fear-strangers-criminals",
			"power-control-issues",
		],
	},
]
