// Import shared metadata for both conditions and pioneers
// Using dynamic import with fallback paths for proper Netlify Edge Function resolution
let CONDITIONS_METADATA = []
let PIONEERS_METADATA = []
let metadataLoaded = false

async function loadMetadata() {
	if (metadataLoaded) return

	try {
		// Try importing from co-located metadata file (generated by build process)
		const module = await import("./conditions-metadata.js")
		CONDITIONS_METADATA = module.CONDITIONS_METADATA || []
		PIONEERS_METADATA = module.PIONEERS_METADATA || []
		console.log(
			`✓ Loaded metadata from co-located file: ${CONDITIONS_METADATA.length} conditions`,
		)
	} catch (importError) {
		console.warn(
			"Could not import from co-located file:",
			importError.message,
		)
		try {
			// Fallback to source path
			const module = await import("../../src/data/conditions-metadata.js")
			CONDITIONS_METADATA = module.CONDITIONS_METADATA || []
			PIONEERS_METADATA = module.PIONEERS_METADATA || []
			console.log(
				`✓ Loaded metadata from src: ${CONDITIONS_METADATA.length} conditions`,
			)
		} catch (sourceError) {
			console.error(
				"Failed to import metadata from any location:",
				sourceError.message,
			)
			console.log("No metadata available for condition matching")
		}
	}

	// Build the CONDITIONS array after loading metadata
	buildConditionsArray()
	metadataLoaded = true
}

// Map of condition IDs to their names (extracted from Conditions.js)
const CONDITIONS_NAMES = {
	"depressed-suicidal-major-depressive-disorder":
		"Depressed, Suicidal and/or Major Depressive Disorder",
	"developmental-trauma-childhood-trauma":
		"Developmental Trauma (Childhood Trauma)",
	"divorce-relational-trauma-family-systems-stress":
		"Divorce? - Relational Trauma and Family Systems Stress",
	"ptsd-post-traumatic-stress-disorder":
		"PTSD - Post-Traumatic Stress Disorder",
	"migraine-headache": "Migraine - Chronic Headache",
	"stutter-fluency-stammer": "Stutter - Speech Fluency",
	"arachnophobia-fear-spiders": "Arachnophobia - Fear of Spiders",
	"ophidiophobia-fear-snakes": "Ophidiophobia - Fear of Snakes",
	"acrophobia-fear-heights": "Acrophobia - Fear of Heights",
	"glossophobia-fear-public-speaking":
		"Glossophobia - Fear of Public Speaking",
	"agoraphobia-social-phobia": "Agoraphobia/Social Phobia",
	"aerophobia-fear-flying": "Aerophobia - Fear of Flying",
	"trypanophobia-fear-needles": "Trypanophobia - Fear of Needles",
	"cynophobia-fear-dogs": "Cynophobia - Fear of Dogs",
	"claustrophobia-fear-enclosed-spaces":
		"Claustrophobia - Fear of Enclosed Spaces",
	"astraphobia-fear-storms": "Astraphobia - Fear of Storms",
	"asd-autism-spectrum": "ASD - Autism Spectrum Disorder",
	"adhd-attention-deficit": "ADHD - Attention Deficit Hyperactivity Disorder",
	"bipolar-mood-disorder": "Bipolar - Mood Disorder",
	"rage-anger-ied": "Rage - Intermittent Explosive Disorder",
	"addiction-substance-abuse": "Addiction - Substance Abuse",
	"tics-tourette": "Tics - Tourette Syndrome",
	"epilepsy-seizure": "Epilepsy - Seizure Disorder",
	"ocd-obsessive-compulsive": "OCD - Obsessive-Compulsive Disorder",
	"spd-sensory-processing-disorder": "SPD - Sensory Processing Disorder",
	"misophonia-selective-sound": "Misophonia - Selective Sound Sensitivity",
	"mutism-selective-silence": "Selective Mutism - Communication Disorder",
	"dyspraxia-motor-coordination": "Dyspraxia - Motor Coordination Disorder",
	"dyscalculia-math-numbers": "Dyscalculia - Math Learning Disorder",
	"dysgraphia-writing-handwriting": "Dysgraphia - Writing Disorder",
}

// Map of pioneer IDs to their names (extracted from Pioneers.js)
const PIONEERS_NAMES = {
	"paul-maclean": "Paul MacLean",
	"daniel-goleman": "Daniel Goleman",
	"gul-dolen": "Gül Dölen",
	"ann-graybiel": "Ann Graybiel",
	"carla-shatz": "Carla Shatz",
	"trevor-robbins": "Trevor Robbins",
	"erin-schuman": "Erin Schuman",
	"giacomo-indiveri": "Giacomo Indiveri",
	"yukiyasu-kamitani": "Yukiyasu Kamitani",
	"aditya-murthy": "Aditya Murthy",
	"bo-li": "Bo Li",
	"mary-galea": "Mary Galea",
	"daniel-wegner": "Daniel M. Wegner",
	"karl-friston": "Karl Friston",
	"karim-nader": "Karim Nader",
	"olivier-hardt": "Olivier Hardt",
	"daniela-schiller": "Daniela Schiller",
}

// Combine all routes: conditions and pioneers
// This ensures paths and background images stay in sync
let CONDITIONS = []

function buildConditionsArray() {
	CONDITIONS = [
		...CONDITIONS_METADATA.map((meta) => ({
			...meta,
			name: CONDITIONS_NAMES[meta.id] || "",
		})),
		...PIONEERS_METADATA.map((meta) => ({
			...meta,
			name: PIONEERS_NAMES[meta.id] || "",
		})),
	]
	return CONDITIONS
}

/**
 * Score a condition based on word matches with position and field priority weighting
 * (Same logic as src/lib/Conditions.js for consistency)
 */
function scoreCondition(condition, words) {
	const condId = condition.id.toLowerCase()
	const condPath = condition.path.toLowerCase()
	const condName = condition.name.toLowerCase()
	const condDesc = (condition.description || "").toLowerCase()

	const pathSegments = condPath.split("/").filter(Boolean)

	let totalScore = 0
	let matchingWordCount = 0

	for (let wordIndex = 0; wordIndex < words.length; wordIndex++) {
		const word = words[wordIndex]
		let wordScore = 0

		const pathPosition = pathSegments.findIndex((seg) => seg.includes(word))
		if (pathPosition !== -1) {
			const positionBonus = 100 - pathPosition * 15
			wordScore += positionBonus
			matchingWordCount++
		}

		if (condName.includes(word)) {
			wordScore += 50 + (10 - wordIndex * 2)
			if (pathPosition === -1) matchingWordCount++
		}

		if (condId.includes(word)) {
			wordScore += 30
			if (pathPosition === -1 && !condName.includes(word))
				matchingWordCount++
		}

		if (condDesc.includes(word) && wordScore < 5) {
			wordScore += 5
		}

		totalScore += wordScore
	}

	const frequencyBonus = 1 + matchingWordCount * 0.2
	return totalScore * frequencyBonus
}

/**
 * Find best matching condition (mirrors src/lib/Conditions.js)
 */
function getCondition(words) {
	if (!words || words.length === 0) return null

	let bestCondition = null
	let bestScore = -1

	for (const condition of CONDITIONS) {
		const score = scoreCondition(condition, words)
		if (score > bestScore) {
			bestScore = score
			bestCondition = condition
		}
	}

	return bestScore > 0 ? bestCondition : null
}

export default async (request, context) => {
	// Load metadata on first request
	await loadMetadata()

	const url = new URL(request.url)
	const pathname = url.pathname

	// Skip for static and non-query routes
	if (
		pathname === "/" ||
		pathname === "/careers" ||
		pathname === "/consent" ||
		pathname === "/success" ||
		pathname.startsWith("/static/") ||
		pathname.startsWith("/api/") ||
		pathname.startsWith("/images/") ||
		pathname.endsWith(".js") ||
		pathname.endsWith(".css")
	) {
		return
	}

	// Get the response
	const response = await context.next()

	// Only modify HTML responses
	if (!response.headers.get("content-type")?.includes("text/html")) {
		return response
	}

	// Extract the path (e.g., "/love" -> "love") and find best matching condition
	const path = pathname.slice(1)
	let matchedCondition = null

	if (path) {
		const words = path
			.toLowerCase()
			.split(/[\s-_/]+/)
			.filter(Boolean)

		matchedCondition = getCondition(words)
	}

	// If we found a matching condition, rewrite og tags
	if (matchedCondition) {
		let html = await response.text()

		// Inject verification meta tag before closing </head>
		html = html.replace(
			/<\/head>/i,
			`<meta name="x-edge-function" content="rewrite-og-tags" />\n<meta name="x-og-matched" content="${matchedCondition.id}" />\n<meta name="x-og-image" content="${matchedCondition.background_image || "none"}" />\n</head>`,
		)

		// Replace og:url - handle any whitespace/newlines
		html = html.replace(
			/<meta\s+property="og:url"[^>]*>/i,
			`<meta property="og:url" content="${request.url.replace(/"/g, "&quot;")}" />`,
		)

		// Replace og:title - handle any whitespace/newlines
		html = html.replace(
			/<meta\s+property="og:title"[^>]*>/i,
			`<meta property="og:title" content="${matchedCondition.name.replace(/"/g, "&quot;")}" />`,
		)

		// Replace og:description - handle any whitespace/newlines
		html = html.replace(
			/<meta\s+property="og:description"[^>]*>/i,
			`<meta property="og:description" content="A comprehensive research program addressing ${matchedCondition.name.toLowerCase()}" />`,
		)

		// Replace og:image - use watermarked image from API if background image exists
		// Pass only the path to the API endpoint (e.g., "/backgrounds/condition.png")
		// The API will resolve it as a local static file
		const ogImageUrl = matchedCondition.background_image
			? `https://neurorecursion.com/api/image?url=${encodeURIComponent(matchedCondition.background_image)}&width=1200&height=630&watermark=true`
			: "https://neurorecursion.com/ogfamily.png"
		html = html.replace(
			/<meta\s+property="og:image"[^>]*>/i,
			`<meta property="og:image" content="${ogImageUrl}" />`,
		)

		// Create new response with modified headers
		const headers = new Headers(response.headers)
		headers.set("cache-control", "public, max-age=3600")

		return new Response(html, {
			status: response.status,
			statusText: response.statusText,
			headers: headers,
		})
	}

	return response
}

export const config = {
	path: "/*",
}
